# coding: utf-8

# flake8: noqa

"""
    Smart Tribune V2 API

    The purpose of this API is to allow developers to build front-end interfaces for displaying knowledge base data (Faq, Helpbox, Chatbot ...) ## Authorization and API Requests To access the API, all requests need an api-token to be passed in the Authorization request header as a bearer token. **Authorization**: Bearer api-token You can retrieve your api-token using the POST request to **/v1/auth**.  ## Rate Limiting  We currently limit the number of API requests per IP address on a specific window of 1s. When the rate limit is exceeded for a given API endpoint, the API will return either HTTP 429 Too Many Requests or HTTP 503 Service Unavailable response.  ### Find below Standard API rate limits per window:  | Endpoints | User limit per window | |---|---| | POST  */v1/auth* | 2 | | GET   */v1/knowledge-bases* | 2 | | POST  */v1/knowledge-bases/{id}/filtered/questions* | 10 | | POST  */v1/knowledge-bases/{id}/filtered/thematics* | 10 | | GET   */v1/knowledge-bases/{id}/questions/{questionId}/channels/{channelId}/responses* | 10 | | POST  */v1/knowledge-bases/{id}/questions/{questionId}/responses/{responseId}/responses-satisfactions* | 2 | | GET   */v1/knowledge-bases/{id}/reasons* | 2 | | GET   */v1/knowledge-bases/{id}/reasons-comments* | 2 | | PATCH */v1/knowledge-bases/{id}/questions/{questionId}/responses/{responseId}/responses-satisfactions/{satisfactionId}* | 2 | | GET */v1/knowledge-bases/{id}/contacts* | 2 |   # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: devs@smart-tribune.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.authentication_api import AuthenticationApi
from swagger_client.api.filtered_api_api import FilteredAPIApi
from swagger_client.api.generic_api_api import GenericAPIApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.any_of_filtered_questions_payload_search_filters_items import AnyOfFilteredQuestionsPayloadSearchFiltersItems
from swagger_client.models.any_of_filtered_questions_payload_search_filters_operators_items import AnyOfFilteredQuestionsPayloadSearchFiltersOperatorsItems
from swagger_client.models.any_of_filtered_thematics_payload_search_filters_items import AnyOfFilteredThematicsPayloadSearchFiltersItems
from swagger_client.models.auth import Auth
from swagger_client.models.channel import Channel
from swagger_client.models.contact import Contact
from swagger_client.models.contact_configuration import ContactConfiguration
from swagger_client.models.content import Content
from swagger_client.models.error import Error
from swagger_client.models.filtered_questions_data import FilteredQuestionsData
from swagger_client.models.filtered_questions_data_linked_question import FilteredQuestionsDataLinkedQuestion
from swagger_client.models.filtered_questions_payload import FilteredQuestionsPayload
from swagger_client.models.filtered_thematics_payload import FilteredThematicsPayload
from swagger_client.models.forbidden_error import ForbiddenError
from swagger_client.models.image import Image
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response2003 import InlineResponse2003
from swagger_client.models.inline_response2004 import InlineResponse2004
from swagger_client.models.inline_response2005 import InlineResponse2005
from swagger_client.models.inline_response2006 import InlineResponse2006
from swagger_client.models.inline_response2007 import InlineResponse2007
from swagger_client.models.inline_response2008 import InlineResponse2008
from swagger_client.models.inline_response2009 import InlineResponse2009
from swagger_client.models.knowledge_base import KnowledgeBase
from swagger_client.models.language import Language
from swagger_client.models.meta import Meta
from swagger_client.models.meta_with_query import MetaWithQuery
from swagger_client.models.not_found_error import NotFoundError
from swagger_client.models.reason import Reason
from swagger_client.models.reason_comment import ReasonComment
from swagger_client.models.response import Response
from swagger_client.models.response_id_responsessatisfactions_body import ResponseIdResponsessatisfactionsBody
from swagger_client.models.responsessatisfactions_satisfaction_id_body import ResponsessatisfactionsSatisfactionIdBody
from swagger_client.models.search_filters_operators_tag import SearchFiltersOperatorsTag
from swagger_client.models.search_filters_operators_thematic import SearchFiltersOperatorsThematic
from swagger_client.models.search_filters_tag_name import SearchFiltersTagName
from swagger_client.models.search_filters_thematic_name import SearchFiltersThematicName
from swagger_client.models.search_filters_thematic_slug import SearchFiltersThematicSlug
from swagger_client.models.service_unavailable_error import ServiceUnavailableError
from swagger_client.models.tag import Tag
from swagger_client.models.thematic import Thematic
from swagger_client.models.too_many_request_error import TooManyRequestError
from swagger_client.models.unauthorized_error import UnauthorizedError
