# coding: utf-8

"""
    Smart Tribune V2 API

    The purpose of this API is to allow developers to build front-end interfaces for displaying knowledge base data (Faq, Helpbox, Chatbot ...) ## Authorization and API Requests To access the API, all requests need an api-token to be passed in the Authorization request header as a bearer token. **Authorization**: Bearer api-token You can retrieve your api-token using the POST request to **/v1/auth**.  ## Rate Limiting  We currently limit the number of API requests per IP address on a specific window of 1s. When the rate limit is exceeded for a given API endpoint, the API will return either HTTP 429 Too Many Requests or HTTP 503 Service Unavailable response.  ### Find below Standard API rate limits per window:  | Endpoints | User limit per window | |---|---| | POST  */v1/auth* | 2 | | GET   */v1/knowledge-bases* | 2 | | POST  */v1/knowledge-bases/{id}/filtered/questions* | 10 | | POST  */v1/knowledge-bases/{id}/filtered/thematics* | 10 | | GET   */v1/knowledge-bases/{id}/questions/{questionId}/channels/{channelId}/responses* | 10 | | POST  */v1/knowledge-bases/{id}/questions/{questionId}/responses/{responseId}/responses-satisfactions* | 2 | | GET   */v1/knowledge-bases/{id}/reasons* | 2 | | GET   */v1/knowledge-bases/{id}/reasons-comments* | 2 | | PATCH */v1/knowledge-bases/{id}/questions/{questionId}/responses/{responseId}/responses-satisfactions/{satisfactionId}* | 2 | | GET */v1/knowledge-bases/{id}/contacts* | 2 |   # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: devs@smart-tribune.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'system_name': 'str',
        'name': 'str',
        'locale': 'str',
        'method': 'str',
        'knowledge_base_id': 'int',
        'contact_configuration': 'ContactConfiguration'
    }

    attribute_map = {
        'id': 'id',
        'system_name': 'systemName',
        'name': 'name',
        'locale': 'locale',
        'method': 'method',
        'knowledge_base_id': 'knowledgeBaseId',
        'contact_configuration': 'contactConfiguration'
    }

    def __init__(self, id=None, system_name=None, name=None, locale=None, method=None, knowledge_base_id=None, contact_configuration=None):  # noqa: E501
        """Contact - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._system_name = None
        self._name = None
        self._locale = None
        self._method = None
        self._knowledge_base_id = None
        self._contact_configuration = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if system_name is not None:
            self.system_name = system_name
        if name is not None:
            self.name = name
        if locale is not None:
            self.locale = locale
        if method is not None:
            self.method = method
        if knowledge_base_id is not None:
            self.knowledge_base_id = knowledge_base_id
        if contact_configuration is not None:
            self.contact_configuration = contact_configuration

    @property
    def id(self):
        """Gets the id of this Contact.  # noqa: E501


        :return: The id of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Contact.


        :param id: The id of this Contact.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def system_name(self):
        """Gets the system_name of this Contact.  # noqa: E501


        :return: The system_name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._system_name

    @system_name.setter
    def system_name(self, system_name):
        """Sets the system_name of this Contact.


        :param system_name: The system_name of this Contact.  # noqa: E501
        :type: str
        """

        self._system_name = system_name

    @property
    def name(self):
        """Gets the name of this Contact.  # noqa: E501


        :return: The name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Contact.


        :param name: The name of this Contact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def locale(self):
        """Gets the locale of this Contact.  # noqa: E501


        :return: The locale of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Contact.


        :param locale: The locale of this Contact.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def method(self):
        """Gets the method of this Contact.  # noqa: E501


        :return: The method of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this Contact.


        :param method: The method of this Contact.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def knowledge_base_id(self):
        """Gets the knowledge_base_id of this Contact.  # noqa: E501


        :return: The knowledge_base_id of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._knowledge_base_id

    @knowledge_base_id.setter
    def knowledge_base_id(self, knowledge_base_id):
        """Sets the knowledge_base_id of this Contact.


        :param knowledge_base_id: The knowledge_base_id of this Contact.  # noqa: E501
        :type: int
        """

        self._knowledge_base_id = knowledge_base_id

    @property
    def contact_configuration(self):
        """Gets the contact_configuration of this Contact.  # noqa: E501


        :return: The contact_configuration of this Contact.  # noqa: E501
        :rtype: ContactConfiguration
        """
        return self._contact_configuration

    @contact_configuration.setter
    def contact_configuration(self, contact_configuration):
        """Sets the contact_configuration of this Contact.


        :param contact_configuration: The contact_configuration of this Contact.  # noqa: E501
        :type: ContactConfiguration
        """

        self._contact_configuration = contact_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
